<?php

use \Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function accession_reference_theme(): array {
  $item = ['render element' => 'elements'];
  return [
    'accession_reference_item' => $item,
    'accession_reference_widget' => $item,
  ];
}

/**
 * @param array $variables
 * @return void
 */
function accession_reference_common_preprocess(array &$variables): void {
  $elements = $variables['elements'];
  $variables['title'] = $elements['#title'];
  $variables['title_display'] = $elements['#title_display'];
  $variables['title_attributes'] = $elements['#title_attributes'] ?? new Attribute();

  $variables['description'] = $elements['#description'];
  $variables['description_display'] = $elements['#description_display'];
  $variables['description_attributes'] = $elements['#description_attributes'] ?? new Attribute();

  $variables['content']['groupref'] = [
    'attributes' => new Attribute($elements['groupref']['#attributes']),
    'value' => $elements['groupref']['#default_value'],
  ];
  $variables['content']['separator'] = [
    'attributes' => new Attribute($elements['separator']['#attributes']),
    'value' => $elements['separator']['#value'],
  ];
  $variables['content']['itemref'] = [
    'attributes' => new Attribute($elements['itemref']['#attributes']),
    'value' => $elements['itemref']['#default_value'],
  ];
}

/**
 * Prepares variables for accession reference item template.
 */
function accession_reference_preprocess_accession_reference_item(array &$variables): void {
  accession_reference_common_preprocess($variables);
}

/**
 * Prepares variables for accession reference widget template.
 */
function accession_reference_preprocess_accession_reference_widget(array &$variables): void {
  accession_reference_common_preprocess($variables);
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function accession_reference_theme_suggestions_accession_reference_item(array $variables): array {
  $field_name = $variables['elements']['#field_name'] ?? '';
  if (!empty($field_name)) {
    return ['accession_reference_item__' . $field_name];
  }
  return [];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function accession_reference_theme_suggestions_accession_reference_widget(array $variables): array {
  $field_name = $variables['elements']['#field_name'] ?? '';
  if (!empty($field_name)) {
    return ['accession_reference_widget__' . $field_name];
  }
  return [];
}
