# Schema for the configuration files of the Accession Reference module.

# Formatters schema.
field.formatter.settings.accession_reference:
  type: mapping
  label: 'Accession Reference format settings'
  mapping:
    zeropad_groupref:
      type: boolean
      label: 'Zero Pad the Group ref'
    zeropad_itemref:
      type: boolean
      label: 'Zero Pad the Item ref'

# Widget schema.
field.widget.settings.accession_reference:
  type: mapping
  label: 'Accession Reference format settings'
  mapping:
    groupref_placeholder:
      type: string
      label: 'Placeholder for groupref'
    groupref_min:
      type: integer
      label: 'Minimum value of the groupref.'
    groupref_max:
      type: integer
      label: 'Maximum value of the groupref.'
    itemref_placeholder:
      type: string
      label: 'Placeholder for item ref'
    itemref_min:
      type: integer
      label: 'Minimum value of the groupref.'
    itemref_max:
      type: integer
      label: 'Maximum value of the itemref field'

# Storage schema.
field.storage_settings.accession_reference:
  type: mapping
  label: 'Accession Reference data'
  mapping:
    groupref:
      type: string
      label: 'Group ref'
    itemref:
      type: string
      label: 'Item ref'
    options:
      type: mapping
      label: 'Accession Reference options'

# Instance schema.
field.field_settings.accession_reference:
  type: mapping
  label: 'Accession Reference settings'
  mapping:
    separator:
      type: string
      label: 'Reference separator character'

# Default value schema.
field.value.accession_reference:
  type: mapping
  label: 'Default value'
  mapping:
    groupref:
      type: string
      label: 'Group ref'
    itemref:
      type: string
      label: 'Item ref'
    options:
      type: mapping
      label: 'Accession Reference options'
